const NEW_GENESIS_META = {
  24: {
    name: "Titan Core",
    image: "/assets/nfts/titan_core.png",
    gradient: "linear-gradient(135deg, #f5a623 0%, #f76b1c 100%)",
    description: "A glowing, massive crystalline core pulsing with orange energy. The heart of a fallen colossus.",
    glowColor: "#f5a623",
  },
  25: {
    name: "Neural Nexus",
    image: "/assets/nfts/neural_nexus.png",
    gradient: "linear-gradient(135deg, #00d2ff 0%, #3a7bd5 100%)",
    description: "An intricate network of glowing fiber optics forming a synthetic brain structure.",
    glowColor: "#00d2ff",
  },
  26: {
    name: "Quantum Sentinel",
    image: "/assets/nfts/quantum_sentinel.png",
    gradient: "linear-gradient(135deg, #9d50bb 0%, #6e48aa 100%)",
    description: "A floating robotic guardian that monitors the quantum flow of the network.",
    glowColor: "#9d50bb",
  },
  27: {
    name: "Cybernetic Aegis",
    image: "/assets/nfts/cybernetic_aegis.png",
    gradient: "linear-gradient(135deg, #e1eec3 0%, #f05053 100%)",
    description: "A high-tech defensive shield forged in the fires of the protocol wars.",
    glowColor: "#f05053",
  },
  28: {
    name: "Orbital Relay",
    image: "/assets/nfts/orbital_relay.png",
    gradient: "linear-gradient(135deg, #2b5876 0%, #4e4376 100%)",
    description: "Synchronizes activity with low-orbit satellite relays for global operations.",
    glowColor: "#4e4376",
  },
  29: {
    name: "Data Monolith",
    image: "/assets/nfts/data_monolith.png",
    gradient: "linear-gradient(135deg, #434343 0%, #000000 100%)",
    description: "A massive block of encrypted data storage containing forgotten archives.",
    glowColor: "#ffffff",
  },
  30: {
    name: "Plasma Overdrive",
    image: "/assets/nfts/plasma_overdrive.png",
    gradient: "linear-gradient(135deg, #ff9966 0%, #ff5e62 100%)",
    description: "Increases the energy output of any connected system to extreme levels.",
    glowColor: "#ff5e62",
  },
  31: {
    name: "Void Singularity",
    image: "/assets/nfts/void_singularity.png",
    gradient: "linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)",
    description: "A localized gravity well that can consume and compress large data sets.",
    glowColor: "#302b63",
  },
  32: {
    name: "Neon Catalyst",
    image: "/assets/nfts/neon_catalyst.png",
    gradient: "linear-gradient(135deg, #1d976c 0%, #93f9b9 100%)",
    description: "A biological booster for network performance. Stimulates rapid growth.",
    glowColor: "#93f9b9",
  },
  33: {
    name: "System Override",
    image: "/assets/nfts/system_override.png",
    gradient: "linear-gradient(135deg, #000000 0%, #533483 100%)",
    description: "Bypasses standard security protocols without leaving a trace.",
    glowColor: "#533483",
  },
  34: {
    name: "Protocol Ghost",
    image: "/assets/nfts/protocol_ghost.png",
    gradient: "linear-gradient(135deg, #232526 0%, #414345 100%)",
    description: "An ethereal software pattern that mimics legitimate system traffic.",
    glowColor: "#888888",
  },
  35: {
    name: "Encryption Key Alpha",
    image: "/assets/nfts/encryption_key_alpha.png",
    gradient: "linear-gradient(135deg, #ffd89b 0%, #19033d 100%)",
    description: "The ultimate access key for high-level data silos.",
    glowColor: "#ffd89b",
  },
  36: {
    name: "Nano-Swarm",
    image: "/assets/nfts/nano_swarm.png",
    gradient: "linear-gradient(135deg, #304352 0%, #d7d2cc 100%)",
    description: "A cloud of microscopic drones used for distributed processing.",
    glowColor: "#d7d2cc",
  },
  37: {
    name: "Holo-Map",
    image: "/assets/nfts/holo_map.png",
    gradient: "linear-gradient(135deg, #00bf8f 0%, #001510 100%)",
    description: "A detailed holographic map of the protocol network and its hidden nodes.",
    glowColor: "#00bf8f",
  },
  38: {
    name: "Pulse Cannon",
    image: "/assets/nfts/pulse_cannon.png",
    gradient: "linear-gradient(135deg, #c31432 0%, #240b36 100%)",
    description: "A heavy-duty defensive weapon used to repel brute-force attacks.",
    glowColor: "#c31432",
  },
  39: {
    name: "Binary Sword",
    image: "/assets/nfts/binary_sword.png",
    gradient: "linear-gradient(135deg, #4ca1af 0%, #c4e0e5 100%)",
    description: "A digital blade capable of cutting through the strongest encryption.",
    glowColor: "#4ca1af",
  },
  40: {
    name: "Vector Shield",
    image: "/assets/nfts/vector_shield.png",
    gradient: "linear-gradient(135deg, #11998e 0%, #38ef7d 100%)",
    description: "Deflects incoming data packets and protects against DDoS surges.",
    glowColor: "#38ef7d",
  },
  41: {
    name: "Static Pulse",
    image: "/assets/nfts/static_pulse.png",
    gradient: "linear-gradient(135deg, #2c3e50 0%, #bdc3c7 100%)",
    description: "A short-range burst that scrambles nearby telemetry.",
    glowColor: "#bdc3c7",
  },
  42: {
    name: "Copper Link",
    image: "/assets/nfts/copper_link.png",
    gradient: "linear-gradient(135deg, #b79891 0%, #94716b 100%)",
    description: "A basic physical connector for legacy hardware integration.",
    glowColor: "#b79891",
  },
  43: {
    name: "Basic Uplink",
    image: "/assets/nfts/basic_uplink.png",
    gradient: "linear-gradient(135deg, #4b6cb7 0%, #182848 100%)",
    description: "Standard networking module for low-bandwidth communication.",
    glowColor: "#4b6cb7",
  },
  44: {
    name: "Scrap Drone",
    image: "/assets/nfts/scrap_drone.png",
    gradient: "linear-gradient(135deg, #5D4157 0%, #A8CABA 100%)",
    description: "A salvaged drone re-purposed for simple data transport.",
    glowColor: "#A8CABA",
  },
  45: {
    name: "Rusty Cipher",
    image: "/assets/nfts/rusty_cipher.png",
    gradient: "linear-gradient(135deg, #3E5151 0%, #DECBA4 100%)",
    description: "A worn-out encryption device from the early protocol era.",
    glowColor: "#DECBA4",
  },
  46: {
    name: "Patch-Work Shield",
    image: "/assets/nfts/patchwork_shield.png",
    gradient: "linear-gradient(135deg, #606c88 0%, #3f4c6b 100%)",
    description: "A defensive layer made of various salvaged materials.",
    glowColor: "#606c88",
  },
  47: {
    name: "Titan Core",
    image: "/assets/nfts/titan_core.png",
    gradient: "linear-gradient(135deg, #f5a623 0%, #f76b1c 100%)",
    description: "A glowing, massive crystalline core pulsing with orange energy. The heart of a fallen colossus.",
    glowColor: "#f5a623",
  }
};
