const FULL_COLLECTION_DRAFT = {
  1: { name: "Origin Shard", rarity: "LEGENDARY", desc: "The very first data fragment crystallized from the protocol birth." },
  2: { name: "Echo of Titan", rarity: "LEGENDARY", desc: "A resonant frequency from the first successful core ignition." },
  3: { name: "Bifrost Bridge", rarity: "LEGENDARY", desc: "A shimmering connection between legacy and modern protocol layers." },
  4: { name: "Void Pulse", rarity: "LEGENDARY", desc: "A heartbeat detected in the empty space between data packets." },
  5: { name: "Chronos Key", rarity: "LEGENDARY", desc: "A temporal artifact capable of viewing past network states." },
  6: { name: "Static Ghost", rarity: "RARE", desc: "A persistent silhouette formed from background radiation." },
  7: { name: "Memory Leech", rarity: "RARE", desc: "A parasitic process that slowly recovers lost sector data." },
  8: { name: "Firewall Spike", rarity: "RARE", desc: "A jagged defensive structure from the pre-v2 era." },
  9: { name: "Cipher Dust", rarity: "RARE", desc: "Microscopic bits of broken encryption scattered across the grid." },
  10: { name: "Logic Storm", rarity: "RARE", desc: "A localized weather pattern composed entirely of boolean contradictions." },
  11: { name: "Neural Static", rarity: "RARE", desc: "The sound of ten thousand minds trying to sync at once." },
  12: { name: "Silicon Fossil", rarity: "RARE", desc: "A preserved hardware component from the first server farm." },
  13: { name: "Proxy Wraith", rarity: "RARE", desc: "A semi-autonomous routing entity that ignores standard hop limits." },
  14: { name: "Data Siphon", rarity: "RARE", desc: "A crude tool for drawing energy from nearby high-traffic nodes." },
  15: { name: "Grid Flare", rarity: "RARE", desc: "A sudden burst of illumination in the dark web's deep sectors." },
  16: { name: "Scrap Key", rarity: "UNCOMMON", desc: "A roughly carved access token made of recycled hardware." },
  17: { name: "Bit Streamer", rarity: "UNCOMMON", desc: "A low-level data carrier used for bulk file transfers." },
  18: { name: "Buffer Shell", rarity: "UNCOMMON", desc: "A temporary storage container designed to absorb overflow lag." },
  19: { name: "Ping Sentinel", rarity: "UNCOMMON", desc: "A simple bot that alerts the network when a node goes dark." },
  20: { name: "Link Router", rarity: "UNCOMMON", desc: "A standard junction point for suburban network clusters." },
  21: { name: "Packet Drone", rarity: "UNCOMMON", desc: "A small, fast-moving delivery unit for priority mail." },
  22: { name: "Cache Fragment", rarity: "UNCOMMON", desc: "A piece of a temporary file that was never meant to be permanent." },
  23: { name: "Node Beacon", rarity: "UNCOMMON", desc: "A simple lighthouse for lost telemetry packets." },
  24: { name: "Protocol Junk", rarity: "UNCOMMON", desc: "A collection of miscellaneous bits with no clear purpose, yet." },
  // 25-47 already defined
};
